# Generated by Django 5.2.4 on 2025-07-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0020_remove_estudiante_cursos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="profesor",
        ),
        migrations.AlterField(
            model_name="curso",
            name="nombre",
            field=models.IntegerField(
                choices=[
                    (1, "PRIMERO"),
                    (2, "SEGUNDO"),
                    (3, "TERCERO"),
                    (4, "CUARTO"),
                    (5, "QUINTO"),
                    (6, "SEXTO"),
                    (7, "SEPTIMO"),
                    (8, "OCTAVO"),
                    (9, "NOVENO"),
                    (10, "DECIMO"),
                    (11, "ONCE"),
                ],
                unique=True,
            ),
        ),
    ]
