# Generated by Django 5.2.4 on 2025-07-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0018_alter_actividad_comentario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividad",
            name="periodo_academico",
            field=models.IntegerField(
                choices=[(1, "PRIMERO"), (2, "SEGUNDO"), (3, "TERCERO")]
            ),
        ),
    ]
