# Generated by Django 5.2.4 on 2025-07-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0019_alter_actividad_periodo_academico"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudiante",
            name="cursos",
        ),
    ]
