# Generated by Django 5.2.4 on 2025-07-31 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0021_remove_curso_profesor_alter_curso_nombre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nota",
            name="nombre",
        ),
    ]
